### PR TITLE
Alert

### PR DESCRIPTION
**Pull request by parulgupta2001**
Please review

### CODE REVIEW

**Review by dev-enforced — APPROVED** [review]
The code changes look good to me. It would be better to provide a detail of the components you have added along with pictures and live previews while making the PR

**Comment by parulgupta2001** [comment]
> The code changes look good to me. It would be better to provide a detail of the components you have added along with pictures and live previews while making the PR

Ok

**Review by zoef-yt — APPROVED** [review]
Looks good to me. Good to merge.

**Review by humzahasan — APPROVED** [review]
Good to merge! Good use of class name and good structure maintained.

**Comment by sumitk-singh** [comment]
coded in structured way, looks good, you can merge.

**Pull request merged**
